comment:
  on-update: recreate
  header: |
    Compilation Issues Found

  footer: |
    ---
    This is an automated comment created by the Bonsol CI

  snippets:
    - id: check_{{ outhash }}
      files:
        - '*.txt'
      body: |
        ```
        {{ outcontent }}
        ```
        
        