// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class CompleteProof {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CompleteProof {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

seal(index: number):number|null {
    return this.bb!.readUint8(this.bb_pos + 0 + index);
}

input(index: number):number|null {
    return this.bb!.readUint8(this.bb_pos + 256 + index);
}

static sizeOf():number {
  return 384;
}

static createCompleteProof(builder:flatbuffers.Builder, seal: number[]|null, input: number[]|null):flatbuffers.Offset {
  builder.prep(1, 384);

  for (let i = 127; i >= 0; --i) {
    builder.writeInt8((input?.[i] ?? 0));

  }


  for (let i = 255; i >= 0; --i) {
    builder.writeInt8((seal?.[i] ?? 0));

  }

  return builder.offset();
}

}
