// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum InputType {
  Unknown = 0,
  PublicData = 1,
  PublicAccountData = 3,
  PublicUrl = 4,
  Private = 5,
  PublicProof = 7,
  PrivateLocal = 8
}
