// automatically generated by the FlatBuffers compiler, do not modify

export enum InputType {
  Unknown = 0,
  PublicData = 1,
  PublicAccountData = 3,
  PublicUrl = 4,
  Private = 5,
  InputSet = 6,
  PublicProof = 7,
  PrivateLocal = 8
}
