// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Input, InputT } from './input.js';


export class InputSet implements flatbuffers.IUnpackableObject<InputSetT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InputSet {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInputSet(bb:flatbuffers.ByteBuffer, obj?:InputSet):InputSet {
  return (obj || new InputSet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInputSet(bb:flatbuffers.ByteBuffer, obj?:InputSet):InputSet {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InputSet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

inputs(index: number, obj?:Input):Input|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Input()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

inputsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startInputSet(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addInputs(builder:flatbuffers.Builder, inputsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, inputsOffset, 0);
}

static createInputsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startInputsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endInputSet(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishInputSetBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedInputSetBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createInputSet(builder:flatbuffers.Builder, inputsOffset:flatbuffers.Offset):flatbuffers.Offset {
  InputSet.startInputSet(builder);
  InputSet.addInputs(builder, inputsOffset);
  return InputSet.endInputSet(builder);
}

unpack(): InputSetT {
  return new InputSetT(
    this.bb!.createObjList<Input, InputT>(this.inputs.bind(this), this.inputsLength())
  );
}


unpackTo(_o: InputSetT): void {
  _o.inputs = this.bb!.createObjList<Input, InputT>(this.inputs.bind(this), this.inputsLength());
}
}

export class InputSetT implements flatbuffers.IGeneratedObject {
constructor(
  public inputs: (InputT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const inputs = InputSet.createInputsVector(builder, builder.createObjectOffsetList(this.inputs));

  return InputSet.createInputSet(builder,
    inputs
  );
}
}
