// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ProgramInputType {
  Unknown = 0,
  Public = 1,
  Private = 2,
  PublicProof = 3
}
