// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ProverVersion {
  DEFAULT = 0,
  V1_0_1 = 1,
  V1_2_1 = 9
}
