// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum StatusTypes {
  Unknown = 0,
  Queued = 1,
  Claimed = 2,
  Completed = 3,
  Failed = 4
}
