// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use crate::execution_request_v1_generated::*;
use crate::status_v1_generated::*;
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_CHANNEL_INSTRUCTION_DATA: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_CHANNEL_INSTRUCTION_DATA: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_CHANNEL_INSTRUCTION_DATA: [ChannelInstructionData; 3] = [
  ChannelInstructionData::NONE,
  ChannelInstructionData::ExecuteV1,
  ChannelInstructionData::StatusV1,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ChannelInstructionData(pub u8);
#[allow(non_upper_case_globals)]
impl ChannelInstructionData {
  pub const NONE: Self = Self(0);
  pub const ExecuteV1: Self = Self(1);
  pub const StatusV1: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::ExecuteV1,
    Self::StatusV1,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::ExecuteV1 => Some("ExecuteV1"),
      Self::StatusV1 => Some("StatusV1"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ChannelInstructionData {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ChannelInstructionData {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for ChannelInstructionData {
    type Output = ChannelInstructionData;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for ChannelInstructionData {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ChannelInstructionData {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ChannelInstructionData {}
pub struct ChannelInstructionDataUnionTableOffset {}

pub enum ChannelInstructionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChannelInstruction<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ChannelInstruction<'a> {
  type Inner = ChannelInstruction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ChannelInstruction<'a> {
  pub const VT_INSTRUCTION_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_INSTRUCTION: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ChannelInstruction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ChannelInstructionArgs
  ) -> flatbuffers::WIPOffset<ChannelInstruction<'bldr>> {
    let mut builder = ChannelInstructionBuilder::new(_fbb);
    if let Some(x) = args.instruction { builder.add_instruction(x); }
    builder.add_instruction_type(args.instruction_type);
    builder.finish()
  }


  #[inline]
  pub fn instruction_type(&self) -> ChannelInstructionData {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ChannelInstructionData>(ChannelInstruction::VT_INSTRUCTION_TYPE, Some(ChannelInstructionData::NONE)).unwrap()}
  }
  #[inline]
  pub fn instruction(&self) -> Option<flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(ChannelInstruction::VT_INSTRUCTION, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn instruction_as_execute_v1(&self) -> Option<ExecutionRequestV1<'a>> {
    if self.instruction_type() == ChannelInstructionData::ExecuteV1 {
      self.instruction().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { ExecutionRequestV1::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn instruction_as_status_v1(&self) -> Option<StatusV1<'a>> {
    if self.instruction_type() == ChannelInstructionData::StatusV1 {
      self.instruction().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { StatusV1::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for ChannelInstruction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_union::<ChannelInstructionData, _>("instruction_type", Self::VT_INSTRUCTION_TYPE, "instruction", Self::VT_INSTRUCTION, false, |key, v, pos| {
        match key {
          ChannelInstructionData::ExecuteV1 => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ExecutionRequestV1>>("ChannelInstructionData::ExecuteV1", pos),
          ChannelInstructionData::StatusV1 => v.verify_union_variant::<flatbuffers::ForwardsUOffset<StatusV1>>("ChannelInstructionData::StatusV1", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct ChannelInstructionArgs {
    pub instruction_type: ChannelInstructionData,
    pub instruction: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for ChannelInstructionArgs {
  #[inline]
  fn default() -> Self {
    ChannelInstructionArgs {
      instruction_type: ChannelInstructionData::NONE,
      instruction: None,
    }
  }
}

pub struct ChannelInstructionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ChannelInstructionBuilder<'a, 'b> {
  #[inline]
  pub fn add_instruction_type(&mut self, instruction_type: ChannelInstructionData) {
    self.fbb_.push_slot::<ChannelInstructionData>(ChannelInstruction::VT_INSTRUCTION_TYPE, instruction_type, ChannelInstructionData::NONE);
  }
  #[inline]
  pub fn add_instruction(&mut self, instruction: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChannelInstruction::VT_INSTRUCTION, instruction);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ChannelInstructionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ChannelInstructionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ChannelInstruction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ChannelInstruction<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ChannelInstruction");
      ds.field("instruction_type", &self.instruction_type());
      match self.instruction_type() {
        ChannelInstructionData::ExecuteV1 => {
          if let Some(x) = self.instruction_as_execute_v1() {
            ds.field("instruction", &x)
          } else {
            ds.field("instruction", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        ChannelInstructionData::StatusV1 => {
          if let Some(x) = self.instruction_as_status_v1() {
            ds.field("instruction", &x)
          } else {
            ds.field("instruction", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("instruction", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ChannelInstruction`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_channel_instruction_unchecked`.
pub fn root_as_channel_instruction(buf: &[u8]) -> Result<ChannelInstruction, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<ChannelInstruction>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ChannelInstruction` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_channel_instruction_unchecked`.
pub fn size_prefixed_root_as_channel_instruction(buf: &[u8]) -> Result<ChannelInstruction, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<ChannelInstruction>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ChannelInstruction` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_channel_instruction_unchecked`.
pub fn root_as_channel_instruction_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ChannelInstruction<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<ChannelInstruction<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ChannelInstruction` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_channel_instruction_unchecked`.
pub fn size_prefixed_root_as_channel_instruction_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ChannelInstruction<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<ChannelInstruction<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ChannelInstruction and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ChannelInstruction`.
pub unsafe fn root_as_channel_instruction_unchecked(buf: &[u8]) -> ChannelInstruction {
  flatbuffers::root_unchecked::<ChannelInstruction>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ChannelInstruction and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ChannelInstruction`.
pub unsafe fn size_prefixed_root_as_channel_instruction_unchecked(buf: &[u8]) -> ChannelInstruction {
  flatbuffers::size_prefixed_root_unchecked::<ChannelInstruction>(buf)
}
#[inline]
pub fn finish_channel_instruction_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<ChannelInstruction<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_channel_instruction_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<ChannelInstruction<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
