// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use crate::input_type_generated::*;

extern crate flatbuffers;

pub enum InputSetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct InputSet<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for InputSet<'a> {
    type Inner = InputSet<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> InputSet<'a> {
    pub const VT_INPUTS: flatbuffers::VOffsetT = 4;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        InputSet { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args InputSetArgs<'args>,
    ) -> flatbuffers::WIPOffset<InputSet<'bldr>> {
        let mut builder = InputSetBuilder::new(_fbb);
        if let Some(x) = args.inputs {
            builder.add_inputs(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn inputs(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Input<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Input>>,
            >>(InputSet::VT_INPUTS, None)
        }
    }
}

impl flatbuffers::Verifiable for InputSet<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Input>>,
            >>("inputs", Self::VT_INPUTS, false)?
            .finish();
        Ok(())
    }
}
pub struct InputSetArgs<'a> {
    pub inputs: Option<
        flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Input<'a>>>>,
    >,
}
impl<'a> Default for InputSetArgs<'a> {
    #[inline]
    fn default() -> Self {
        InputSetArgs { inputs: None }
    }
}

pub struct InputSetBuilder<'a: 'b, 'b> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> InputSetBuilder<'a, 'b> {
    #[inline]
    pub fn add_inputs(
        &mut self,
        inputs: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<Input<'b>>>,
        >,
    ) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(InputSet::VT_INPUTS, inputs);
    }
    #[inline]
    pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> InputSetBuilder<'a, 'b> {
        let start = _fbb.start_table();
        InputSetBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<InputSet<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for InputSet<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("InputSet");
        ds.field("inputs", &self.inputs());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `InputSet`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_input_set_unchecked`.
pub fn root_as_input_set(buf: &[u8]) -> Result<InputSet, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<InputSet>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `InputSet` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_input_set_unchecked`.
pub fn size_prefixed_root_as_input_set(
    buf: &[u8],
) -> Result<InputSet, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<InputSet>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `InputSet` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_input_set_unchecked`.
pub fn root_as_input_set_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<InputSet<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<InputSet<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `InputSet` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_input_set_unchecked`.
pub fn size_prefixed_root_as_input_set_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<InputSet<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<InputSet<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a InputSet and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `InputSet`.
pub unsafe fn root_as_input_set_unchecked(buf: &[u8]) -> InputSet {
    flatbuffers::root_unchecked::<InputSet>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed InputSet and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `InputSet`.
pub unsafe fn size_prefixed_root_as_input_set_unchecked(buf: &[u8]) -> InputSet {
    flatbuffers::size_prefixed_root_unchecked::<InputSet>(buf)
}
#[inline]
pub fn finish_input_set_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<InputSet<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_input_set_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<InputSet<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
