import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  howToSidebar: [
    {
      type: 'autogenerated',
      dirName: 'how-to-guides',
    },
  ],
  referenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],
  explanationSidebar: [
    {
      type: 'autogenerated',
      dirName: 'explanation',
    },
  ],
};

export default sidebars;
